### ISSUE TITLE
Build Process Doesn't Compile Component JS Automatically

### ISSUE THREAD

**Issue by tarecord** [moderntribe/square-one#698]
According to the documentation in [docs/concepts/components.md](https://github.com/moderntribe/square-one/blob/main/docs/concepts/components.md#javascript):

>Create an index.js file to serve as a clearing-house, loading additional files found in the Component's js directory. The build system will find this index.js and load it (along with anything it imports) into the global JS bundle.

To get the javascript compiling automatically I had to load it within the theme's `components.js`:
https://github.com/moderntribe/square-one/blob/b73599614d5f8bd7fca4e6b610f9acf80feda13c/wp-content/themes/core/assets/js/src/theme/core/components.js#L16-L27

**Comment by ryanurban** [comment]
Yeah that's a good catch and that is correct. We horsed around quite a bit trying to get the same magic going that we have for our CSS via PostCSS, but JS is harder in this regard : ) The simplest path forward is to import and then initialize each component as you register it as you found. Another great documentation clean up PR if you'd like to take it on!

**Comment by dpellenwood** [comment]
You are correct. This is intentional though. JavaScript execution order matters where CSS order does not. There's no way for webpack to "know" if one specific module needs to come before another, so we've opted to leave the imports manual to allow developers to set the correct execution order for their components.
