### ISSUE TITLE
(Post::factory($post_id))->get_meta() doesn't work

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square-one#908]
[Docs reference to use this when accessing meta](https://github.com/moderntribe/square-one/blob/main/docs/basics/object-meta.md?plain=1#L226). Had to fall back to ACF get_field since it doesn't work.

**Comment by defunctl** [comment]
@nickpelton can you show your failing code? You need to use the correct factory for the correct type.

**Comment by nickpelton** [comment]
Sure. I've registered some meta for a Page, in this example `title`. The meta exists on that page (confirmed in DB).

```php
$page = Page::factory( $post_id );
$meta = $page->get_meta( Homepage_Template_Settings::TITLE );
// $meta is null
```

I confirmed `self::title` is in the `get_keys` array of the Meta Group. Tried the Post object as well, no dice. But a simple get_post_meta or a get_field works fine.

**Comment by nickpelton** [comment]
When I traced the code it looks like it was failing at the keys check here `\Tribe\Libs\Object_Meta\Meta_Map::get_value`

**Comment by defunctl** [comment]
Did some tests locally and this is working fine for me, is that from an ACF options page or something?

Can you link to the project, please?

**Comment by nickpelton** [comment]
Yes, it's from the Ongov project repo. `moderntribe/ongov`

**Comment by defunctl** [comment]
If it's an ACF Options page, then those are not stored in postmeta, but stored in the options table, so using the Page object factory should never work since that meta would not exist with that post. Page extends Post in this context, and relates to a WordPress Post Type of "Page".

To grab ACF options settings, see how the General Settings: Analytics system does it:

Inject the Object Meta object into the class you want to use it in: https://github.com/moderntribe/square-one/blob/7239c8191489c30ecafbf61f089ee44c56a5c996/wp-content/plugins/core/src/Integrations/Google_Tag_Manager/GTM_Scripts.php#L11

Note the [get_value() method overload](https://github.com/moderntribe/square-one/blob/ba44b39ecabce2fc4c46be4b99187e55b8644c62/wp-content/plugins/core/src/Object_Meta/Analytics_Settings.php#L25) in the object meta class.

Then, grab your values via the proper constants: https://github.com/moderntribe/square-one/blob/7239c8191489c30ecafbf61f089ee44c56a5c996/wp-content/plugins/core/src/Integrations/Google_Tag_Manager/GTM_Scripts.php#L22

**Comment by nickpelton** [comment]
Sorry I misspoke. It's a Page option for a specific Template, so it _should_ still be Post Meta.

**Comment by defunctl** [comment]
No probs, please link to the files (here or slack) I have real code to check out and it'll be much easier to debug.

**Comment by defunctl** [comment]
Depending on what your data source is (an ACF settings page, or meta attached to a certain content type) you'd use the correct meta object to fetch the data.

**Examples**

Get meta from a taxonomy term:

1. [Create the object via the factory](https://github.com/moderntribe/square-one/blob/70a0edd00f2de5545a54f0ea96f946dbf6304a61/wp-content/themes/core/routes/index/Index_Controller.php#L119)
2. [Fetch the meta using the Meta Object's key](https://github.com/moderntribe/square-one/blob/70a0edd00f2de5545a54f0ea96f946dbf6304a61/wp-content/themes/core/routes/index/Index_Controller.php#L124)

Get meta from an ACF settings page:

1. [Inject your settings object as a dependency](https://github.com/moderntribe/square-one/blob/70a0edd00f2de5545a54f0ea96f946dbf6304a61/wp-content/themes/core/routes/index/Index_Controller.php#L28-L34)
3. [Fetch the setting using the Meta Object's keys](https://github.com/moderntribe/square-one/blob/70a0edd00f2de5545a54f0ea96f946dbf6304a61/wp-content/themes/core/routes/index/Index_Controller.php#L130-L132)

Based on your [example](https://github.com/moderntribe/square-one/issues/908#issuecomment-1007786049) above, you should be using the `Get meta from an ACF settings page` example here, because the data is not attached to any post ID and under the hood is pulled from the `wp_options` table.
